version: "3.7"

services:

  app:
    image: getting-started
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres	
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todos

  postgres:
    image: postgres:14.11
    volumes:
      - ./PGDATA:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todos
